-- ============================================
-- POPULATE FEATURE STORE
-- File: 04-feature-store/populate_feature_store.sql
-- ============================================

USE DATABASE VISTORA_ML_PROJECT;
USE SCHEMA FEATURE_ENGINEERING;
USE WAREHOUSE ML_WAREHOUSE;

-- ============================================
-- STORED PROCEDURE: Load Aggregation Features
-- ============================================

CREATE OR REPLACE PROCEDURE SP_LOAD_AGGREGATION_FEATURES()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    -- Insert aggregation features
    INSERT INTO FEATURE_STORE (
        customer_id, feature_group, feature_name, feature_value, 
        feature_data_type, computation_method, source_tables
    )
    SELECT 
        customer_id,
        'aggregation' AS feature_group,
        'total_revenue' AS feature_name,
        TO_VARIANT(total_revenue) AS feature_value,
        'numeric' AS feature_data_type,
        'SUM(price * quantity)' AS computation_method,
        'RAW_CUSTOMER_TRANSACTIONS' AS source_tables
    FROM VW_CUSTOMER_AGGREGATION_FEATURES
    
    UNION ALL
    
    SELECT 
        customer_id, 'aggregation', 'total_transactions',
        TO_VARIANT(total_transactions), 'numeric',
        'COUNT(DISTINCT transaction_id)', 'RAW_CUSTOMER_TRANSACTIONS'
    FROM VW_CUSTOMER_AGGREGATION_FEATURES
    
    UNION ALL
    
    SELECT 
        customer_id, 'aggregation', 'avg_order_value',
        TO_VARIANT(avg_order_value), 'numeric',
        'AVG(price * quantity)', 'RAW_CUSTOMER_TRANSACTIONS'
    FROM VW_CUSTOMER_AGGREGATION_FEATURES
    
    UNION ALL
    
    SELECT 
        customer_id, 'behavioral', 'preferred_category',
        TO_VARIANT(preferred_category), 'categorical',
        'MODE(product_category)', 'RAW_CUSTOMER_TRANSACTIONS'
    FROM VW_CUSTOMER_AGGREGATION_FEATURES
    
    UNION ALL
    
    SELECT 
        customer_id, 'behavioral', 'preferred_device',
        TO_VARIANT(preferred_device), 'categorical',
        'MODE(device_type)', 'RAW_CUSTOMER_TRANSACTIONS'
    FROM VW_CUSTOMER_AGGREGATION_FEATURES
    
    UNION ALL
    
    SELECT 
        customer_id, 'temporal', 'days_since_last_purchase',
        TO_VARIANT(days_since_last_purchase), 'numeric',
        'DATEDIFF(day, MAX(transaction_date), CURRENT_TIMESTAMP)', 
        'RAW_CUSTOMER_TRANSACTIONS'
    FROM VW_CUSTOMER_AGGREGATION_FEATURES;
    
    RETURN 'Aggregation features loaded successfully';
END;
$$;

-- ============================================
-- STORED PROCEDURE: Load RFM Features
-- ============================================

CREATE OR REPLACE PROCEDURE SP_LOAD_RFM_FEATURES()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO FEATURE_STORE (
        customer_id, feature_group, feature_name, feature_value,
        feature_data_type, computation_method, source_tables
    )
    SELECT 
        customer_id, 'rfm', 'recency_score',
        TO_VARIANT(recency_score), 'numeric',
        'NTILE(5) OVER (ORDER BY recency)', 'RAW_CUSTOMER_TRANSACTIONS'
    FROM VW_RFM_FEATURES
    
    UNION ALL
    
    SELECT 
        customer_id, 'rfm', 'frequency_score',
        TO_VARIANT(frequency_score), 'numeric',
        'NTILE(5) OVER (ORDER BY frequency)', 'RAW_CUSTOMER_TRANSACTIONS'
    FROM VW_RFM_FEATURES
    
    UNION ALL
    
    SELECT 
        customer_id, 'rfm', 'monetary_score',
        TO_VARIANT(monetary_score), 'numeric',
        'NTILE(5) OVER (ORDER BY monetary)', 'RAW_CUSTOMER_TRANSACTIONS'
    FROM VW_RFM_FEATURES
    
    UNION ALL
    
    SELECT 
        customer_id, 'rfm', 'rfm_segment',
        TO_VARIANT(rfm_segment), 'categorical',
        'CONCAT(R,F,M scores)', 'RAW_CUSTOMER_TRANSACTIONS'
    FROM VW_RFM_FEATURES
    
    UNION ALL
    
    SELECT 
        customer_id, 'rfm', 'customer_lifecycle_segment',
        TO_VARIANT(customer_lifecycle_segment), 'categorical',
        'CASE statement on RFM scores', 'RAW_CUSTOMER_TRANSACTIONS'
    FROM VW_RFM_FEATURES
    
    UNION ALL
    
    SELECT 
        customer_id, 'rfm', 'churn_risk',
        TO_VARIANT(churn_risk), 'categorical',
        'CASE on recency_days', 'RAW_CUSTOMER_TRANSACTIONS'
    FROM VW_RFM_FEATURES;
    
    RETURN 'RFM features loaded successfully';
END;
$$;

-- ============================================
-- STORED PROCEDURE: Update Feature Metadata
-- ============================================

CREATE OR REPLACE PROCEDURE SP_UPDATE_FEATURE_METADATA()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO FEATURE_METADATA (
        feature_group, feature_name, feature_description,
        feature_data_type, feature_category, update_frequency, owner, team
    )
    VALUES
        ('aggregation', 'total_revenue', 'Total revenue generated by customer', 
         'numeric', 'transactional', 'daily', 'ML Team', 'Analytics'),
        ('aggregation', 'total_transactions', 'Total number of transactions',
         'numeric', 'transactional', 'daily', 'ML Team', 'Analytics'),
        ('aggregation', 'avg_order_value', 'Average order value',
         'numeric', 'transactional', 'daily', 'ML Team', 'Analytics'),
        ('behavioral', 'preferred_category', 'Most frequently purchased category',
         'categorical', 'behavioral', 'weekly', 'ML Team', 'Analytics'),
        ('behavioral', 'preferred_device', 'Most frequently used device',
         'categorical', 'behavioral', 'weekly', 'ML Team', 'Analytics'),
        ('temporal', 'days_since_last_purchase', 'Days since last transaction',
         'numeric', 'temporal', 'daily', 'ML Team', 'Analytics'),
        ('rfm', 'recency_score', 'RFM Recency score (1-5)',
         'numeric', 'segmentation', 'weekly', 'ML Team', 'Analytics'),
        ('rfm', 'frequency_score', 'RFM Frequency score (1-5)',
         'numeric', 'segmentation', 'weekly', 'ML Team', 'Analytics'),
        ('rfm', 'monetary_score', 'RFM Monetary score (1-5)',
         'numeric', 'segmentation', 'weekly', 'ML Team', 'Analytics'),
        ('rfm', 'customer_lifecycle_segment', 'Customer lifecycle classification',
         'categorical', 'segmentation', 'weekly', 'ML Team', 'Analytics'),
        ('rfm', 'churn_risk', 'Customer churn risk level',
         'categorical', 'risk', 'daily', 'ML Team', 'Analytics');
    
    RETURN 'Feature metadata updated successfully';
END;
$$;

-- ============================================
-- EXECUTE ALL PROCEDURES
-- ============================================

-- Load aggregation features
CALL SP_LOAD_AGGREGATION_FEATURES();

-- Load RFM features
CALL SP_LOAD_RFM_FEATURES();

-- Update metadata
CALL SP_UPDATE_FEATURE_METADATA();

-- ============================================
-- VERIFICATION QUERIES
-- ============================================

-- Check total features loaded
SELECT 
    feature_group,
    COUNT(*) AS feature_count,
    COUNT(DISTINCT customer_id) AS customer_count
FROM FEATURE_STORE
WHERE is_active = TRUE
GROUP BY feature_group
ORDER BY feature_group;

-- Check metadata
SELECT * FROM FEATURE_METADATA ORDER BY feature_group, feature_name;

-- Sample features for one customer
SELECT 
    customer_id,
    feature_group,
    feature_name,
    feature_value,
    created_at
FROM FEATURE_STORE
WHERE customer_id = (SELECT customer_id FROM FEATURE_STORE LIMIT 1)
AND is_active = TRUE
ORDER BY feature_group, feature_name;

SELECT 'Feature Store populated successfully!' AS status;